server:
  port: 443
  ssl:
    key-store: classpath:*****.pfx
    key-store-password: *****
    keyStoreType: PKCS12
spring:
  application:
    name: gateway-web
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes:
        - id: express
          uri: lb://express
          predicates:
            - Path=/express/**
        - id: bargain
          uri: lb://bargain
          predicates:
            - Path=/bargain/**
        - id: login
          uri: lb://login
          predicates:
            - Path=/login/**
        - id: play
          uri: lb://play
          predicates:
            - Path=/play/**,/water/**
        - id: system
          uri: lb://system
          predicates:
            - Path=/system/**,/send/**
        - id: seckill
          uri: lb://seckill
          predicates:
            - Path=/seckill/**,/seckillSet/**
eureka:
  client:
    service-url:
      defaultZone: http://*****/eureka
  instance:
    prefer-ip-address: true
management:
  endpoint:
    gateway:
      enabled: true
    web:
      exposure:
        include: true
