server:
  port: 12309
spring:
  application:
    name: system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///*****
    username: *****
    password: *****
  redis:
    host: 127.0.0.1
    port: 6379
  dubbo:
    application:            #应用配置，用于配置当前应用信息，不管该应用是提供者还是消费者。
      name: system
    registry:                 #注册中心配置，用于配置连接注册中心相关信息。
      address: zookeeper://******:*****
    protocol:     #协议配置，用于配置提供服务的协议信息，协议由提供方指定，消费方被动接受。
      name: dubbo
      port: 20880
    provider:
      timeout: 30000
    #扫描注解包通过该设置将服务注册到zookeeper
    base-package: com.qiruipeng.sys.service.impl

eureka:
  client:
    service-url:
      defaultZone: http://*****/eureka